// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdoJM6l5yAaxOmuhs0i4oadhvTk_J-YM',
    appId: '1:585220726368:web:f8396b099b06220889ad05',
    messagingSenderId: '585220726368',
    projectId: 'liskfitai-204a7',
    authDomain: 'liskfitai-204a7.firebaseapp.com',
    storageBucket: 'liskfitai-204a7.appspot.com',
    measurementId: 'G-57HJ4GDYSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVl5YBFaW18Gj6kML9qObHt5WAWNkPWQ0',
    appId: '1:585220726368:android:355e152f9517d0b489ad05',
    messagingSenderId: '585220726368',
    projectId: 'liskfitai-204a7',
    storageBucket: 'liskfitai-204a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDus1eA-NO0ExVe3u4m9Bq8S-Rg-qJLKeI',
    appId: '1:585220726368:ios:fe401aedefb292e889ad05',
    messagingSenderId: '585220726368',
    projectId: 'liskfitai-204a7',
    storageBucket: 'liskfitai-204a7.appspot.com',
    androidClientId: '585220726368-7bep28vo89ngt847uobiiaddtdv04jju.apps.googleusercontent.com',
    iosClientId: '585220726368-bcg8i89bm43t1k39jl2lb761ril2gvi7.apps.googleusercontent.com',
    iosBundleId: 'com.app.liskfitai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDus1eA-NO0ExVe3u4m9Bq8S-Rg-qJLKeI',
    appId: '1:585220726368:ios:fe401aedefb292e889ad05',
    messagingSenderId: '585220726368',
    projectId: 'liskfitai-204a7',
    storageBucket: 'liskfitai-204a7.appspot.com',
    androidClientId: '585220726368-7bep28vo89ngt847uobiiaddtdv04jju.apps.googleusercontent.com',
    iosClientId: '585220726368-bcg8i89bm43t1k39jl2lb761ril2gvi7.apps.googleusercontent.com',
    iosBundleId: 'com.app.liskfitai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEdoJM6l5yAaxOmuhs0i4oadhvTk_J-YM',
    appId: '1:585220726368:web:1d2b440e2fb159cb89ad05',
    messagingSenderId: '585220726368',
    projectId: 'liskfitai-204a7',
    authDomain: 'liskfitai-204a7.firebaseapp.com',
    storageBucket: 'liskfitai-204a7.appspot.com',
    measurementId: 'G-K14TLWS3JQ',
  );
}
